codecov:
  ci:
    - github.com
    - gitlab.com
    - circleci.com
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: '70..100'
  status:
    project:
      default:
        target: auto
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 10%
        if_ci_failed: error

comment:
  layout: 'diff, flags, files'
  behavior: default
  require_changes: false
